version: '3'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres_denticadentistry
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher_denticadentistry
    restart: unless-stopped
    ports:
      - 1080:1080 # Expose the MailCatcher web interface
      - 1025:1025 # Expose the SMTP port for email catching

volumes:
  postgres:
    driver: local
