name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        shm_size: '4gb'
        container_name: postgres_denticadentistry
        environment:
          - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
          - 5432:5432
        volumes:
          - postgres:/var/lib/postgresql/data

      mailcatcher:
        image: schickling/mailcatcher
        container_name: mailcatcher_denticadentistry
        ports:
          - 1080:1080 # Expose the MailCatcher web interface
          - 1025:1025 # Expose the SMTP port for email catching

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Docker Compose
      run: docker-compose up -d

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Ustaw odpowiednią wersję .NET 6.0, np. 6.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release ./DenticaDentistry.sln

    - name: Publish the API project
      run: dotnet publish --configuration Release --no-build --output ./publish ./DenticaDentistry/DenticaDentistry.Api

    - name: Set up environment variables
      run: echo "DOTNET_ROOT=${DOTNET_ROOT}" >> $GITHUB_ENV

    - name: Run the API
      run: dotnet ./publish/DenticaDentistry.Api.dll

    - name: Teardown Docker Compose
      run: docker-compose down
